package com.prog2.main;

import javax.swing.DefaultListModel;

public class mainFrame extends javax.swing.JFrame {

	/**
	 * Creates new form mainFrame
	 */
	public mainFrame() {
		initComponents();
		jTabbedPane2.setSelectedIndex(0);
		jButton1.doClick();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jTabbedPane2 = new javax.swing.JTabbedPane();
		jPanel1 = new javax.swing.JPanel();
		jScrollPane2 = new javax.swing.JScrollPane();
		jLstDep = new javax.swing.JList<>();
		jLabel2 = new javax.swing.JLabel();
		jLblID = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		jTxtFldID = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jLabel3 = new javax.swing.JLabel();
		jLblDean = new javax.swing.JLabel();
		jLabel17 = new javax.swing.JLabel();
		jButton3 = new javax.swing.JButton();
		jPanel2 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jList1 = new javax.swing.JList<>();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();
		jLabel14 = new javax.swing.JLabel();
		jLabel15 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jTextField2 = new javax.swing.JTextField();
		jTextField3 = new javax.swing.JTextField();
		jBSaveChg = new javax.swing.JButton();
		jTextField4 = new javax.swing.JTextField();
		jComboBox1 = new javax.swing.JComboBox<>();
		jTextField5 = new javax.swing.JTextField();
		jTextField6 = new javax.swing.JTextField();
		jTextField7 = new javax.swing.JTextField();
		jTextField8 = new javax.swing.JTextField();
		jComboBox2 = new javax.swing.JComboBox<>();
		jTextField9 = new javax.swing.JTextField();
		jTextField10 = new javax.swing.JTextField();
		jCheckBox1 = new javax.swing.JCheckBox();
		jButton6 = new javax.swing.JButton();
		jButton7 = new javax.swing.JButton();
		jLabel38 = new javax.swing.JLabel();
		jTextField29 = new javax.swing.JTextField();
		jPanel3 = new javax.swing.JPanel();
		jScrollPane3 = new javax.swing.JScrollPane();
		jList2 = new javax.swing.JList<>();
		jLabel16 = new javax.swing.JLabel();
		jTextField11 = new javax.swing.JTextField();
		jLabel18 = new javax.swing.JLabel();
		jTextField12 = new javax.swing.JTextField();
		jLabel19 = new javax.swing.JLabel();
		jTextField13 = new javax.swing.JTextField();
		jLabel20 = new javax.swing.JLabel();
		jTextField14 = new javax.swing.JTextField();
		jLabel21 = new javax.swing.JLabel();
		jComboBox3 = new javax.swing.JComboBox<>();
		jLabel22 = new javax.swing.JLabel();
		jTextField15 = new javax.swing.JTextField();
		jLabel23 = new javax.swing.JLabel();
		jTextField16 = new javax.swing.JTextField();
		jLabel24 = new javax.swing.JLabel();
		jTextField17 = new javax.swing.JTextField();
		jLabel25 = new javax.swing.JLabel();
		jTextField18 = new javax.swing.JTextField();
		jLabel26 = new javax.swing.JLabel();
		jComboBox4 = new javax.swing.JComboBox<>();
		jLabel27 = new javax.swing.JLabel();
		jTextField19 = new javax.swing.JTextField();
		jLabel28 = new javax.swing.JLabel();
		jTextField20 = new javax.swing.JTextField();
		jCheckBox2 = new javax.swing.JCheckBox();
		jButton4 = new javax.swing.JButton();
		jLabel41 = new javax.swing.JLabel();
		jTextField31 = new javax.swing.JTextField();
		jButton8 = new javax.swing.JButton();
		jButton9 = new javax.swing.JButton();
		jLabel39 = new javax.swing.JLabel();
		jTextField30 = new javax.swing.JTextField();
		jPanel4 = new javax.swing.JPanel();
		jScrollPane4 = new javax.swing.JScrollPane();
		jList3 = new javax.swing.JList<>();
		jLabel29 = new javax.swing.JLabel();
		jTextField21 = new javax.swing.JTextField();
		jLabel30 = new javax.swing.JLabel();
		jTextField22 = new javax.swing.JTextField();
		jLabel31 = new javax.swing.JLabel();
		jTextField23 = new javax.swing.JTextField();
		jLabel32 = new javax.swing.JLabel();
		jTextField24 = new javax.swing.JTextField();
		jLabel33 = new javax.swing.JLabel();
		jComboBox5 = new javax.swing.JComboBox<>();
		jLabel34 = new javax.swing.JLabel();
		jTextField25 = new javax.swing.JTextField();
		jLabel35 = new javax.swing.JLabel();
		jTextField26 = new javax.swing.JTextField();
		jLabel36 = new javax.swing.JLabel();
		jTextField27 = new javax.swing.JTextField();
		jLabel37 = new javax.swing.JLabel();
		jTextField28 = new javax.swing.JTextField();
		jButton5 = new javax.swing.JButton();
		jButton10 = new javax.swing.JButton();
		jButton11 = new javax.swing.JButton();
		jLabel40 = new javax.swing.JLabel();
		jTextField32 = new javax.swing.JTextField();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLstDep.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jLstDep.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
		jLstDep.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
			public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
				jLstDepValueChanged(evt);
			}
		});
		jScrollPane2.setViewportView(jLstDep);

		jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jLabel2.setText("Department ID");

		jLblID.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jLblID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

		jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jLabel1.setText("New ID");

		jTxtFldID.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N

		jButton1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jButton1.setText("Refresh");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jButton2.setText("Add new ID");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jLabel3.setText("Dean");

		jLblDean.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jLblDean.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

		jLabel17.setFont(new java.awt.Font("Ubuntu", 0, 28)); // NOI18N
		jLabel17.setForeground(java.awt.Color.red);
		jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel17.setText("Welcome to Vaniley College application systems");

		jButton3.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jButton3.setText("Save all");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 279,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
												.addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 179,
														Short.MAX_VALUE)
												.addComponent(
														jButton1, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(jPanel1Layout.createSequentialGroup()
														.addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE,
																161, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(32, 32, 32).addComponent(jButton3,
																javax.swing.GroupLayout.DEFAULT_SIZE, 179,
																Short.MAX_VALUE))
												.addComponent(jLblID, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jLblDean, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jTxtFldID)))
								.addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 700,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(246, 246, 246)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(48, 48, 48)
						.addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 81,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(45, 45, 45)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 310,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(10, 10, 10)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLblID, javax.swing.GroupLayout.PREFERRED_SIZE, 46,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.PREFERRED_SIZE, 47,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLblDean, javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.PREFERRED_SIZE, 47,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jTxtFldID, javax.swing.GroupLayout.PREFERRED_SIZE, 44,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(56, 56, 56)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jButton1).addComponent(jButton2).addComponent(jButton3))))
						.addContainerGap(368, Short.MAX_VALUE)));

		jTabbedPane2.addTab("Departments", jPanel1);

		jList1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
		jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
			public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
				jList1ValueChanged(evt);
			}
		});
		jScrollPane1.setViewportView(jList1);

		jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jLabel4.setText("ID");

		jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jLabel5.setText("Name");

		jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jLabel6.setText("Address");

		jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jLabel7.setText("Phone");

		jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jLabel8.setText("Gender");

		jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jLabel9.setText("DepartmentID");

		jLabel10.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jLabel10.setText("Department name");

		jLabel11.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jLabel11.setText("Speciality");

		jLabel12.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jLabel12.setText("Degree");

		jLabel13.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jLabel13.setText("Course");

		jLabel14.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jLabel14.setText("Hire date");

		jLabel15.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jLabel15.setText("Years");

		jTextField1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N

		jTextField2.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N

		jTextField3.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N

		jBSaveChg.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jBSaveChg.setText("Save change");
		jBSaveChg.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jBSaveChgActionPerformed(evt);
			}
		});

		jTextField4.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N

		jComboBox1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "m", "f" }));

		jTextField5.setEditable(false);
		jTextField5.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N

		jTextField6.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N

		jTextField7.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N

		jTextField8.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N

		jComboBox2.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Phd", "Master", "Bachelor" }));

		jTextField9.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N

		jTextField10.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N

		jCheckBox1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jCheckBox1.setText("Dean");

		jButton6.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jButton6.setText("New");
		jButton6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton6ActionPerformed(evt);
			}
		});

		jButton7.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jButton7.setText("Save new");
		jButton7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton7ActionPerformed(evt);
			}
		});

		jLabel38.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jLabel38.setText("Salary");

		jTextField29.setEditable(false);
		jTextField29.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap()
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel2Layout.createSequentialGroup().addComponent(jLabel11)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jTextField7))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel2Layout.createSequentialGroup().addComponent(jLabel13).addGap(26, 26, 26)
												.addComponent(jTextField8).addGap(71, 71, 71).addComponent(jLabel12)
												.addGap(65, 65, 65).addComponent(jComboBox2,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(jPanel2Layout.createSequentialGroup().addGroup(jPanel2Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel2Layout.createSequentialGroup().addComponent(jLabel9)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 278,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
												.addGroup(javax.swing.GroupLayout.Alignment.LEADING,
														jPanel2Layout.createSequentialGroup().addComponent(jLabel10)
																.addGap(81, 81, 81).addComponent(jTextField6,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 459,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(jPanel2Layout.createSequentialGroup().addComponent(jLabel6)
														.addGap(239, 239, 239).addComponent(jTextField3,
																javax.swing.GroupLayout.PREFERRED_SIZE, 417,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(javax.swing.GroupLayout.Alignment.LEADING,
														jPanel2Layout.createSequentialGroup().addGroup(jPanel2Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.TRAILING)
																.addGroup(jPanel2Layout.createSequentialGroup()
																		.addComponent(jLabel7).addGap(53, 53, 53)
																		.addComponent(jTextField4,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				158,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGroup(jPanel2Layout
																		.createSequentialGroup().addComponent(jLabel4)
																		.addGap(74, 74, 74).addComponent(jTextField1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				183,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
																.addGroup(jPanel2Layout.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																		.addGroup(jPanel2Layout.createSequentialGroup()
																				.addGap(72, 72, 72)
																				.addComponent(jLabel5)
																				.addPreferredGap(
																						javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE)
																				.addComponent(
																						jTextField2,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						191,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGroup(jPanel2Layout.createSequentialGroup()
																				.addPreferredGap(
																						javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE)
																				.addComponent(jLabel8)
																				.addPreferredGap(
																						javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(jComboBox1,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))))))
										.addGap(0, 0, Short.MAX_VALUE))
								.addGroup(jPanel2Layout.createSequentialGroup()
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel14).addComponent(jBSaveChg).addComponent(jLabel38))
										.addGap(70, 70, 70)
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(jPanel2Layout.createSequentialGroup().addComponent(jButton6)
														.addGap(18, 18, 18).addComponent(jButton7)
														.addGap(0, 0, Short.MAX_VALUE))
												.addGroup(jPanel2Layout.createSequentialGroup().addGroup(jPanel2Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING,
																false)
														.addComponent(jTextField29,
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jTextField9,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE, 214,
																Short.MAX_VALUE))
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(jLabel15).addGap(18, 18, 18)
														.addComponent(jTextField10,
																javax.swing.GroupLayout.PREFERRED_SIZE, 102,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(18, 18, 18).addComponent(jCheckBox1)))))
						.addGap(56, 56, 56)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap()
										.addComponent(jScrollPane1).addGap(55, 55, 55))
								.addGroup(jPanel2Layout.createSequentialGroup().addGap(23, 23, 23)
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel4).addComponent(jLabel5)
												.addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel6)
												.addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel7).addComponent(jLabel8)
												.addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel9).addComponent(jTextField5,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel10).addComponent(jTextField6,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel11).addComponent(jTextField7,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel12).addComponent(jLabel13)
												.addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41,
												Short.MAX_VALUE)
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel14).addComponent(jLabel15)
												.addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jCheckBox1))
										.addGap(41, 41, 41)
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel38).addComponent(jTextField29,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(44, 44, 44)))
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jBSaveChg).addComponent(jButton6).addComponent(jButton7))
						.addGap(215, 215, 215)));

		jTabbedPane2.addTab("FullTimeTeachers", jPanel2);

		jList2.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jList2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
		jList2.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
			public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
				jList2ValueChanged(evt);
			}
		});
		jScrollPane3.setViewportView(jList2);

		jLabel16.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jLabel16.setText("ID");

		jTextField11.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N

		jLabel18.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jLabel18.setText("Name");

		jTextField12.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N

		jLabel19.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jLabel19.setText("Address");

		jTextField13.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N

		jLabel20.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jLabel20.setText("Phone");

		jTextField14.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N

		jLabel21.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jLabel21.setText("Gender");

		jComboBox3.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "m", "f" }));

		jLabel22.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jLabel22.setText("DepartmentID");

		jTextField15.setEditable(false);
		jTextField15.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N

		jLabel23.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jLabel23.setText("Department name");

		jTextField16.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N

		jLabel24.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jLabel24.setText("Speciality");

		jTextField17.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jTextField17.setText("jTextField7");

		jLabel25.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jLabel25.setText("Course");

		jTextField18.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N

		jLabel26.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jLabel26.setText("Degree");

		jComboBox4.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Phd", "Master", "Bachelor" }));

		jLabel27.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jLabel27.setText("Hire date");

		jTextField19.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N

		jLabel28.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jLabel28.setText("Years");

		jTextField20.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N

		jCheckBox2.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jCheckBox2.setText("Dean");

		jButton4.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jButton4.setText("Save change");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		jLabel41.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jLabel41.setText("Woring Hours");

		jTextField31.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N

		jButton8.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jButton8.setText("New");
		jButton8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton8ActionPerformed(evt);
			}
		});

		jButton9.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jButton9.setText("Save new");
		jButton9.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton9ActionPerformed(evt);
			}
		});

		jLabel39.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jLabel39.setText("Salary");

		jTextField30.setEditable(false);
		jTextField30.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup().addContainerGap()
						.addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 279,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(22, 22, 22)
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel3Layout.createSequentialGroup().addComponent(jLabel25).addGap(26, 26, 26)
												.addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 268,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jLabel26).addGap(8, 8, 8).addComponent(jComboBox4,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout
										.createSequentialGroup().addComponent(jLabel24)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addGroup(jPanel3Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addGroup(jPanel3Layout.createSequentialGroup().addGap(127, 127, 127)
														.addComponent(jTextField17))
												.addGroup(jPanel3Layout.createSequentialGroup().addGap(208, 208, 208)
														.addComponent(jTextField16,
																javax.swing.GroupLayout.PREFERRED_SIZE, 277,
																javax.swing.GroupLayout.PREFERRED_SIZE))))
								.addGroup(jPanel3Layout.createSequentialGroup().addGroup(jPanel3Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addGroup(jPanel3Layout.createSequentialGroup().addComponent(jLabel22)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jTextField15))
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout
												.createSequentialGroup().addComponent(jLabel16).addGap(27, 27, 27)
												.addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 104,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jLabel18).addGap(24, 24, 24).addComponent(jTextField12,
														javax.swing.GroupLayout.PREFERRED_SIZE, 191,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout
												.createSequentialGroup()
												.addGroup(jPanel3Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel19).addComponent(jLabel20))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(jPanel3Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addGroup(jPanel3Layout.createSequentialGroup()
																.addGap(11, 11, 11).addComponent(jTextField14,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 216,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
														.addComponent(jTextField13,
																javax.swing.GroupLayout.PREFERRED_SIZE, 417,
																javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addComponent(jLabel23)).addGap(62, 62, 62).addComponent(jLabel21)
										.addGap(18, 18, 18)
										.addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(0, 0, Short.MAX_VALUE))
								.addGroup(jPanel3Layout.createSequentialGroup().addComponent(jLabel27)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13,
												Short.MAX_VALUE)
										.addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, 157,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel28)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, 60,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18).addComponent(jLabel41).addGap(18, 18, 18)
										.addComponent(jTextField31, javax.swing.GroupLayout.PREFERRED_SIZE, 101,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 13,
												Short.MAX_VALUE)
										.addComponent(jCheckBox2))
								.addGroup(jPanel3Layout.createSequentialGroup()
										.addGroup(jPanel3Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(jPanel3Layout.createSequentialGroup().addComponent(jButton4)
														.addGap(34, 34, 34).addComponent(jButton8).addGap(18, 18, 18)
														.addComponent(jButton9).addGap(0, 0, Short.MAX_VALUE))
												.addGroup(jPanel3Layout.createSequentialGroup().addComponent(jLabel39)
														.addGap(70, 70, 70).addComponent(jTextField30)))
										.addContainerGap()))));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup().addContainerGap().addGroup(jPanel3Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
								.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel16).addComponent(jLabel18)
										.addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel19).addComponent(jTextField13,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel20).addComponent(jLabel21)
										.addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel22).addComponent(jTextField15,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel23).addComponent(jTextField16,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel24).addComponent(jTextField17,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel26).addComponent(jLabel25)
										.addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46,
										Short.MAX_VALUE)
								.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel3Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel41).addComponent(jTextField31,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(jPanel3Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel27).addComponent(jLabel28)
												.addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jCheckBox2)))
								.addGap(31, 31, 31)
								.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel39).addComponent(jTextField30,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(37, 37, 37)
								.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel3Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jButton8).addComponent(jButton9))
										.addComponent(jButton4))
								.addContainerGap(238, Short.MAX_VALUE))
						.addGroup(jPanel3Layout.createSequentialGroup()
								.addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 512,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))));

		jTabbedPane2.addTab("PartTimeTeachers", jPanel3);

		jList3.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jList3.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
		jList3.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
			public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
				jList3ValueChanged(evt);
			}
		});
		jScrollPane4.setViewportView(jList3);

		jLabel29.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jLabel29.setText("ID");

		jTextField21.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N

		jLabel30.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jLabel30.setText("Name");

		jTextField22.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N

		jLabel31.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jLabel31.setText("Address");

		jTextField23.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N

		jLabel32.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jLabel32.setText("Phone");

		jTextField24.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N

		jLabel33.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jLabel33.setText("Gender");

		jComboBox5.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "m", "f" }));

		jLabel34.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jLabel34.setText("DepartmentID");

		jTextField25.setEditable(false);
		jTextField25.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N

		jLabel35.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jLabel35.setText("Department name");

		jTextField26.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N

		jLabel36.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jLabel36.setText("Duty");

		jTextField27.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N

		jLabel37.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jLabel37.setText("Workload");

		jTextField28.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N

		jButton5.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jButton5.setText("Save change");
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});

		jButton10.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jButton10.setText("New");
		jButton10.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton10ActionPerformed(evt);
			}
		});

		jButton11.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jButton11.setText("Save new");
		jButton11.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton11ActionPerformed(evt);
			}
		});

		jLabel40.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jLabel40.setText("Salary");

		jTextField32.setEditable(false);
		jTextField32.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout
						.createSequentialGroup().addContainerGap().addComponent(jScrollPane4,
								javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(22, 22, 22)
						.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel4Layout.createSequentialGroup().addComponent(jLabel36)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(jPanel4Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(jPanel4Layout.createSequentialGroup()
														.addGap(0, 0, Short.MAX_VALUE).addComponent(jTextField26,
																javax.swing.GroupLayout.PREFERRED_SIZE, 277,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(jPanel4Layout.createSequentialGroup()
														.addComponent(jTextField27,
																javax.swing.GroupLayout.PREFERRED_SIZE, 358,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(0, 0, Short.MAX_VALUE))))
								.addGroup(jPanel4Layout.createSequentialGroup().addGroup(jPanel4Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addGroup(jPanel4Layout.createSequentialGroup().addComponent(jLabel29)
												.addGap(39, 39, 39)
												.addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, 155,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(18, 18, 18).addComponent(jLabel30).addGap(215, 215, 215))
										.addGroup(jPanel4Layout.createSequentialGroup()
												.addGroup(
														jPanel4Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jLabel31).addComponent(jLabel32))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(jPanel4Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addGroup(jPanel4Layout.createSequentialGroup()
																.addGap(11, 11, 11).addComponent(jTextField24,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 194,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
														.addComponent(jTextField23,
																javax.swing.GroupLayout.PREFERRED_SIZE, 417,
																javax.swing.GroupLayout.PREFERRED_SIZE))))
										.addGroup(jPanel4Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(jPanel4Layout.createSequentialGroup()
														.addComponent(jTextField22,
																javax.swing.GroupLayout.PREFERRED_SIZE, 279,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(0, 4, Short.MAX_VALUE))
												.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
														jPanel4Layout.createSequentialGroup().addComponent(jLabel33)
																.addGap(65, 65, 65)
																.addComponent(jComboBox5,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addContainerGap())))
								.addGroup(jPanel4Layout.createSequentialGroup().addGroup(jPanel4Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabel34)
										.addGroup(jPanel4Layout.createSequentialGroup().addGap(170, 170, 170)
												.addComponent(jTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, 121,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap())
								.addGroup(jPanel4Layout.createSequentialGroup()
										.addGroup(jPanel4Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(jPanel4Layout.createSequentialGroup().addComponent(jButton5)
														.addGap(64, 64, 64).addComponent(jButton10).addGap(18, 18, 18)
														.addComponent(jButton11))
												.addGroup(jPanel4Layout.createSequentialGroup().addComponent(jLabel37)
														.addGap(26, 26, 26).addComponent(jTextField28,
																javax.swing.GroupLayout.PREFERRED_SIZE, 264,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addComponent(jLabel35)
												.addGroup(jPanel4Layout.createSequentialGroup().addComponent(jLabel40)
														.addGap(51, 51, 51).addComponent(jTextField32)))
										.addGap(31, 31, 31)))));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup().addContainerGap().addGroup(jPanel4Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
						.addGroup(jPanel4Layout.createSequentialGroup().addGroup(jPanel4Layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel29)
								.addComponent(jLabel30)
								.addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel31).addComponent(jTextField23,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel32).addComponent(jLabel33)
										.addComponent(jTextField24, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel34).addComponent(jTextField25,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel35).addComponent(jTextField26,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel36).addComponent(jTextField27,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel37).addComponent(jTextField28,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(21, 21, 21)
								.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel40).addComponent(jTextField32,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48,
										Short.MAX_VALUE)
								.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel4Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jButton10).addComponent(jButton11))
										.addComponent(jButton5)))
						.addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING,
								javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(322, Short.MAX_VALUE)));

		jTabbedPane2.addTab("Staff", jPanel4);

		getContentPane().add(jTabbedPane2, java.awt.BorderLayout.PAGE_START);

		pack();
	}// </editor-fold>

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		DefaultListModel<Department> listModel = new DefaultListModel<>();
		Department.getAllDep().forEach(p -> listModel.addElement(p));
		jLstDep.setModel(listModel);
	}

	private void jLstDepValueChanged(javax.swing.event.ListSelectionEvent evt) {
		if (!evt.getValueIsAdjusting()) {
			int i = jLstDep.getSelectedIndex();
			if (i >= 0) {
				Department d = jLstDep.getSelectedValue();
				jLblID.setText(String.valueOf(d.getDepartmentID()));
				if (d.getDepartmentDean() != null) {
					jLblDean.setText(d.getDepartmentDean().getName());
				} else {
					jLblDean.setText("");
				}

				DefaultListModel<FullTimeTeacher> ftListModel = new DefaultListModel<>();
				d.getFullTimeTeachers().forEach(p -> ftListModel.addElement(p));
				jList1.setModel(ftListModel);
				jTextField5.setText(String.valueOf(d.getDepartmentID()));

				DefaultListModel<PartTimeTeacher> ptListModel = new DefaultListModel<>();
				d.getPartTimeTeachers().forEach(p -> ptListModel.addElement(p));
				jList2.setModel(ptListModel);
				jTextField15.setText(String.valueOf(d.getDepartmentID()));

				DefaultListModel<Staff> stListModel = new DefaultListModel<>();
				d.getStaffs().forEach(p -> stListModel.addElement(p));
				jList3.setModel(stListModel);
				jTextField25.setText(String.valueOf(d.getDepartmentID()));
			}
		}
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		jLblDean.setText("");
		Department nd = new Department();
		nd.setDepartmentID(Integer.valueOf(jTxtFldID.getText()));
		Department.addDepartment(nd);
		DefaultListModel<Department> listModel = new DefaultListModel<>();
		Department.getAllDep().forEach(p -> listModel.addElement(p));
		jLstDep.setModel(listModel);
	}

	private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {
		if (!evt.getValueIsAdjusting()) {
			int i = jList1.getSelectedIndex();
			if (i >= 0) {
				FullTimeTeacher t = (FullTimeTeacher) jList1.getSelectedValue();
				jTextField1.setText(String.valueOf(t.getEmployeeID()));
				jTextField1.setEditable(false);
				jTextField2.setText(t.getName());
				jTextField3.setText(t.getAddress());
				jTextField4.setText(t.getPhoneNum());
				jTextField6.setText(t.getDepartment());
				jTextField7.setText(t.getSpecialty());
				jTextField8.setText(t.getCourse());
				jTextField9.setText(t.getHireDate());
				jTextField10.setText(String.valueOf(t.getYearsOfTeaching()));
				jComboBox1.setSelectedItem("" + t.getGender());
				jComboBox2.setSelectedItem(t.getDegree());
				jCheckBox1.setSelected(t.isDean());
				jTextField29.setText(String.valueOf(t.ComputePayRoll()));
			}
		}
	}

	private void jBSaveChgActionPerformed(java.awt.event.ActionEvent evt) {
		FullTimeTeacher t = (FullTimeTeacher) jList1.getSelectedValue();
		t.setName(jTextField2.getText());
		t.setAddress(jTextField3.getText());
		t.setPhoneNum(jTextField4.getText());
		try {
			t.setDepartmentID(Integer.parseInt(jTextField5.getText()));
		} catch (java.lang.NumberFormatException e) {
		}
		t.setDepartment(jTextField6.getText());
		t.setSpecialty(jTextField7.getText());
		t.setCourse(jTextField8.getText());
		t.setHireDate(jTextField9.getText());
		try {
			t.setYearsOfTeaching(Integer.parseInt(jTextField10.getText()));
		} catch (java.lang.NumberFormatException e) {
		}
		t.setGender(((String) jComboBox1.getSelectedItem()).charAt(0));
		t.setDegree((String) jComboBox2.getSelectedItem());
		t.setDean(jCheckBox1.isSelected());
		if (jCheckBox1.isSelected()) {
			Department d = jLstDep.getSelectedValue();
			d.setDepartmentDean(t);
		}
		jTextField29.setText(String.valueOf(t.ComputePayRoll()));

	}

	private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
		jTextField1.setText("");
		jTextField1.setEditable(true);
		jTextField2.setText("");
		jTextField3.setText("");
		jTextField4.setText("");
		jTextField6.setText("");
		jTextField7.setText("");
		jTextField8.setText("");
		jTextField9.setText("");
		jTextField10.setText("");
		jComboBox1.setSelectedItem("m");
		jComboBox2.setSelectedItem("Pha");
		jCheckBox1.setSelected(false);
	}

	private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {
		FullTimeTeacher t = new FullTimeTeacher();
		try {
			t.setEmployeeID(Integer.parseInt(jTextField1.getText()));
		} catch (java.lang.NumberFormatException e) {
		}
		t.setName(jTextField2.getText());
		t.setAddress(jTextField3.getText());
		t.setPhoneNum(jTextField4.getText());
		try {
			t.setDepartmentID(Integer.parseInt(jTextField5.getText()));
		} catch (java.lang.NumberFormatException e) {
		}
		t.setDepartment(jTextField6.getText());
		t.setSpecialty(jTextField7.getText());
		t.setCourse(jTextField8.getText());
		t.setHireDate(jTextField9.getText());
		try {
			t.setYearsOfTeaching(Integer.parseInt(jTextField10.getText()));
		} catch (java.lang.NumberFormatException e) {
		}
		t.setGender(((String) jComboBox1.getSelectedItem()).charAt(0));
		t.setDegree((String) jComboBox2.getSelectedItem());
		t.setDean(jCheckBox1.isSelected());
		t.setParttimeOrFulltime("FullTime");
		Department d = jLstDep.getSelectedValue();
		if (jCheckBox1.isSelected()) {
			d.setDepartmentDean(t);
		}
		jTextField29.setText(String.valueOf(t.ComputePayRoll()));

		d.addFullTimeTeacher(t);

		DefaultListModel<FullTimeTeacher> ftListModel = new DefaultListModel<>();
		d.getFullTimeTeachers().forEach(p -> ftListModel.addElement(p));
		jList1.setModel(ftListModel);
	}

	private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {
		jTextField11.setText("");
		jTextField11.setEditable(true);
		jTextField12.setText("");
		jTextField13.setText("");
		jTextField14.setText("");
		jTextField16.setText("");
		jTextField17.setText("");
		jTextField18.setText("");
		jTextField19.setText("");
		jTextField20.setText("");
		jComboBox3.setSelectedItem("m");
		jComboBox4.setSelectedItem("Pha");
		jCheckBox2.setSelected(false);
		jTextField31.setText("");
	}

	private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {
		PartTimeTeacher t = new PartTimeTeacher();
		try {
			t.setEmployeeID(Integer.parseInt(jTextField11.getText()));
		} catch (java.lang.NumberFormatException e) {
		}
		t.setName(jTextField12.getText());
		t.setAddress(jTextField13.getText());
		t.setPhoneNum(jTextField14.getText());
		try {
			t.setDepartmentID(Integer.parseInt(jTextField15.getText()));
		} catch (java.lang.NumberFormatException e) {
		}
		t.setDepartment(jTextField16.getText());
		t.setSpecialty(jTextField17.getText());
		t.setCourse(jTextField18.getText());
		t.setHireDate(jTextField19.getText());
		try {
			t.setYearsOfTeaching(Integer.parseInt(jTextField20.getText()));
		} catch (java.lang.NumberFormatException e) {
		}
		t.setGender(((String) jComboBox3.getSelectedItem()).charAt(0));
		t.setDegree((String) jComboBox4.getSelectedItem());
		t.setDean(jCheckBox2.isSelected());
		t.setParttimeOrFulltime("PartTime");
		Department d = jLstDep.getSelectedValue();
		if (jCheckBox2.isSelected()) {
			d.setDepartmentDean(t);
		}
		t.setWorkingHour(Double.valueOf(jTextField31.getText()));
		d.addPartTimeTeacher(t);
		jTextField30.setText(String.valueOf(t.ComputePayRoll()));

		DefaultListModel<PartTimeTeacher> ptListModel = new DefaultListModel<>();
		d.getPartTimeTeachers().forEach(p -> ptListModel.addElement(p));
		jList2.setModel(ptListModel);

	}

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		PartTimeTeacher t = jList2.getSelectedValue();
		t.setName(jTextField12.getText());
		t.setAddress(jTextField13.getText());
		t.setPhoneNum(jTextField14.getText());
		try {
			t.setDepartmentID(Integer.parseInt(jTextField15.getText()));
		} catch (java.lang.NumberFormatException e) {
		}
		t.setDepartment(jTextField16.getText());
		t.setSpecialty(jTextField17.getText());
		t.setCourse(jTextField18.getText());
		t.setHireDate(jTextField19.getText());
		try {
			t.setYearsOfTeaching(Integer.parseInt(jTextField20.getText()));
		} catch (java.lang.NumberFormatException e) {
		}
		t.setGender(((String) jComboBox3.getSelectedItem()).charAt(0));
		t.setDegree((String) jComboBox4.getSelectedItem());
		t.setDean(jCheckBox2.isSelected());
		t.setWorkingHour(Double.valueOf(jTextField31.getText()));
		if (jCheckBox2.isSelected()) {
			Department d = jLstDep.getSelectedValue();
			d.setDepartmentDean(t);
		}
		jTextField30.setText(String.valueOf(t.ComputePayRoll()));
	}

	private void jList2ValueChanged(javax.swing.event.ListSelectionEvent evt) {
		if (!evt.getValueIsAdjusting()) {
			int i = jList2.getSelectedIndex();
			if (i >= 0) {
				PartTimeTeacher t = jList2.getSelectedValue();
				jTextField11.setText(String.valueOf(t.getEmployeeID()));
				jTextField11.setEditable(false);
				jTextField12.setText(t.getName());
				jTextField13.setText(t.getAddress());
				jTextField14.setText(t.getPhoneNum());
				jTextField16.setText(t.getDepartment());
				jTextField17.setText(t.getSpecialty());
				jTextField18.setText(t.getCourse());
				jTextField19.setText(t.getHireDate());
				jTextField20.setText(String.valueOf(t.getYearsOfTeaching()));
				jComboBox3.setSelectedItem("" + t.getGender());
				jComboBox4.setSelectedItem(t.getDegree());
				jCheckBox2.setSelected(t.isDean());
				jTextField31.setText(String.valueOf(t.getWorkingHour()));
				jTextField30.setText(String.valueOf(t.ComputePayRoll()));
			}
		}
	}

	private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {
		jTextField21.setText("");
		jTextField21.setEditable(true);
		jTextField22.setText("");
		jTextField23.setText("");
		jTextField24.setText("");
		jTextField26.setText("");
		jTextField27.setText("");
		jTextField28.setText("");
		jComboBox5.setSelectedItem("m");
	}

	private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {
		Staff t = new Staff();
		try {
			t.setEmployeeID(Integer.parseInt(jTextField21.getText()));
		} catch (java.lang.NumberFormatException e) {
		}
		t.setName(jTextField22.getText());
		t.setAddress(jTextField23.getText());
		t.setPhoneNum(jTextField24.getText());
		try {
			t.setDepartmentID(Integer.parseInt(jTextField25.getText()));
		} catch (java.lang.NumberFormatException e) {
		}
		t.setDepartment(jTextField26.getText());
		t.setDuty(jTextField27.getText());
		t.setWorkload(Double.valueOf(jTextField28.getText()));
		t.setGender(((String) jComboBox4.getSelectedItem()).charAt(0));
		Department d = jLstDep.getSelectedValue();
		d.addStaff(t);
		jTextField32.setText(String.valueOf(t.ComputePayRoll()));
		DefaultListModel<Staff> stListModel = new DefaultListModel<>();
		d.getStaffs().forEach(p -> stListModel.addElement(p));
		jList3.setModel(stListModel);
	}

	private void jList3ValueChanged(javax.swing.event.ListSelectionEvent evt) {
		if (!evt.getValueIsAdjusting()) {
			int i = jList3.getSelectedIndex();
			if (i >= 0) {
				Staff t = jList3.getSelectedValue();
				jTextField21.setText(String.valueOf(t.getEmployeeID()));
				jTextField21.setEditable(false);
				jTextField22.setText(t.getName());
				jTextField23.setText(t.getAddress());
				jTextField24.setText(t.getPhoneNum());
				jTextField26.setText(t.getDepartment());
				jTextField27.setText(t.getDuty());
				jTextField28.setText(String.valueOf(t.getWorkload()));
				jComboBox5.setSelectedItem("" + t.getGender());
				jTextField32.setText(String.valueOf(t.ComputePayRoll()));
			}
		}
	}

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
		Staff t = jList3.getSelectedValue();
		t.setName(jTextField22.getText());
		t.setAddress(jTextField23.getText());
		t.setPhoneNum(jTextField24.getText());
		try {
			t.setDepartmentID(Integer.parseInt(jTextField25.getText()));
		} catch (java.lang.NumberFormatException e) {
		}
		t.setDepartment(jTextField26.getText());
		t.setDuty(jTextField27.getText());
		t.setWorkload(Double.valueOf(jTextField28.getText()));
		t.setGender(((String) jComboBox5.getSelectedItem()).charAt(0));
		jTextField32.setText(String.valueOf(t.ComputePayRoll()));
	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		Department.writeDepartmentFile("departments.txt");
		Department.writeFullTimeTeacherFile("fullTimeTeachers.txt");
		Department.writePartTimeTeacherFile("partTimeTeacher.txt");
		Department.writeStaffsFile("staffs.txt");
	}

	// Variables declaration - do not modify
	private javax.swing.JButton jBSaveChg;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton10;
	private javax.swing.JButton jButton11;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton7;
	private javax.swing.JButton jButton8;
	private javax.swing.JButton jButton9;
	private javax.swing.JCheckBox jCheckBox1;
	private javax.swing.JCheckBox jCheckBox2;
	private javax.swing.JComboBox<String> jComboBox1;
	private javax.swing.JComboBox<String> jComboBox2;
	private javax.swing.JComboBox<String> jComboBox3;
	private javax.swing.JComboBox<String> jComboBox4;
	private javax.swing.JComboBox<String> jComboBox5;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel18;
	private javax.swing.JLabel jLabel19;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel20;
	private javax.swing.JLabel jLabel21;
	private javax.swing.JLabel jLabel22;
	private javax.swing.JLabel jLabel23;
	private javax.swing.JLabel jLabel24;
	private javax.swing.JLabel jLabel25;
	private javax.swing.JLabel jLabel26;
	private javax.swing.JLabel jLabel27;
	private javax.swing.JLabel jLabel28;
	private javax.swing.JLabel jLabel29;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel30;
	private javax.swing.JLabel jLabel31;
	private javax.swing.JLabel jLabel32;
	private javax.swing.JLabel jLabel33;
	private javax.swing.JLabel jLabel34;
	private javax.swing.JLabel jLabel35;
	private javax.swing.JLabel jLabel36;
	private javax.swing.JLabel jLabel37;
	private javax.swing.JLabel jLabel38;
	private javax.swing.JLabel jLabel39;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel40;
	private javax.swing.JLabel jLabel41;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JLabel jLblDean;
	private javax.swing.JLabel jLblID;
	private javax.swing.JList<FullTimeTeacher> jList1;
	private javax.swing.JList<PartTimeTeacher> jList2;
	private javax.swing.JList<Staff> jList3;
	private javax.swing.JList<Department> jLstDep;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JScrollPane jScrollPane4;
	private javax.swing.JTabbedPane jTabbedPane2;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField10;
	private javax.swing.JTextField jTextField11;
	private javax.swing.JTextField jTextField12;
	private javax.swing.JTextField jTextField13;
	private javax.swing.JTextField jTextField14;
	private javax.swing.JTextField jTextField15;
	private javax.swing.JTextField jTextField16;
	private javax.swing.JTextField jTextField17;
	private javax.swing.JTextField jTextField18;
	private javax.swing.JTextField jTextField19;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField20;
	private javax.swing.JTextField jTextField21;
	private javax.swing.JTextField jTextField22;
	private javax.swing.JTextField jTextField23;
	private javax.swing.JTextField jTextField24;
	private javax.swing.JTextField jTextField25;
	private javax.swing.JTextField jTextField26;
	private javax.swing.JTextField jTextField27;
	private javax.swing.JTextField jTextField28;
	private javax.swing.JTextField jTextField29;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField30;
	private javax.swing.JTextField jTextField31;
	private javax.swing.JTextField jTextField32;
	private javax.swing.JTextField jTextField4;
	private javax.swing.JTextField jTextField5;
	private javax.swing.JTextField jTextField6;
	private javax.swing.JTextField jTextField7;
	private javax.swing.JTextField jTextField8;
	private javax.swing.JTextField jTextField9;
	private javax.swing.JTextField jTxtFldID;
	// End of variables declaration
}
